# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nq9gU61BqQOg-NJoteoztErSw_ux4RXR
"""

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import json
# import os
# import io
# import time
# import re
# import os
# import subprocess
# import time
# from pyngrok import ngrok, conf
# import pandas as pd
# import matplotlib.pyplot as plt
# import seaborn as sns
# from google import genai
# from google.genai.types import Type
# from PyPDF2 import PdfReader, errors
# 
# MODEL_NAME = "gemini-2.0-flash"
# MAX_RETRIES = 5
# INITIAL_BACKOFF_SECONDS = 2
# 
# st.set_page_config(
#     page_title="LawMate: Legal Document Analyzer & AI Chat",
#     page_icon="⚖️",
#     layout="wide",
#     initial_sidebar_state="collapsed",
# )
# 
# st.markdown("""
#     <style>
#         body {font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background-color: #0d1117; color: #c9d1d9;}
#         .stApp {background-color: #0d1117;}
#         .title {color: #58a6ff; text-align: center; font-size: 3.5rem; font-weight: bold; margin-top: 2rem; margin-bottom: 0.2rem;}
#         .subtitle {text-align: center; color: #8b949e; font-size: 1.2rem; margin-bottom: 2rem;}
#         .card {background-color: #161b22; padding: 1.5rem; border-radius: 1rem; margin-bottom: 1.5rem; box-shadow: 0 6px 20px rgba(0,0,0,0.5);}
#         .section-title {color: #79c0ff; font-size: 1.6rem; font-weight: 600; margin-bottom: 1rem; border-bottom: 1px solid #30363d; padding-bottom: 0.5rem;}
#         .info-box {background-color: #1e293b; padding: 1.5rem; border-radius: 0.75rem; margin-bottom: 2rem; color: #a0aec0; font-style: italic; border-left: 5px solid #58a6ff;}
#         .footer {text-align: center; color: #8b949e; font-size: 0.9rem; margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #30363d;}
#         .stButton>button {background-color: #238636; color: white; font-weight: bold; height: 3rem; width: 100%;}
#         .stProgress>div>div>div>div {background-color: #58a6ff;}
#         .stFileUploader>div>div>input {border-radius: 0.5rem; padding: 0.5rem;}
#         .stExpanderHeader {background-color: #161b22; border-radius: 0.5rem;}
#     </style>
# """, unsafe_allow_html=True)
# 
# st.markdown('<div class="title">⚖️ LawMate</div>', unsafe_allow_html=True)
# st.markdown('<div class="subtitle">AI-powered Legal Document Analyzer & General Law Assistant</div>', unsafe_allow_html=True)
# 
# GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "AIzaSyCP7ZkAjht7-sxmXynhNSU6j3DdLM7QU9A")
# if not GEMINI_API_KEY or GEMINI_API_KEY == "YOUR_GEMINI_API_KEY_HERE":
#     st.error("❌ Gemini API key missing or placeholder. Please set your actual key.", icon="🚫")
#     st.stop()
# 
# @st.cache_resource
# def get_gemini_client(api_key):
#     return genai.Client(api_key=api_key)
# 
# client = get_gemini_client(GEMINI_API_KEY)
# 
# response_schema = {
#     "type": Type.OBJECT,
#     "properties": {
#         "summary": {"type": Type.STRING, "description": "Concise summary of the legal text."},
#         "key_points": {"type": Type.ARRAY, "items": {"type": Type.STRING}, "description": "List of crucial points or obligations."}
#     }
# }
# 
# def analyze_page(page_text: str, page_num: int) -> dict:
#     prompt = (
#         f"Analyze the following legal text from page {page_num}. "
#         f"Act as 'LawMate', an expert legal assistant. Provide a short, clear summary "
#         f"and list key points in plain English, suitable for a non-lawyer.\n\nText:\n{page_text}"
#     )
#     for attempt in range(MAX_RETRIES):
#         try:
#             response = client.models.generate_content(
#                 model=MODEL_NAME,
#                 contents=[{"text": prompt}],
#                 config={
#                     "responseMimeType": "application/json",
#                     "responseSchema": response_schema,
#                     "temperature": 0.2
#                 }
#             )
#             return json.loads(response.text.strip())
#         except json.JSONDecodeError:
#             return {"summary": "Could not generate summary for this page due to JSON error.", "key_points": []}
#         except Exception as e:
#             if "503" in str(e) or "rate limit" in str(e).lower():
#                 if attempt < MAX_RETRIES - 1:
#                     wait_time = INITIAL_BACKOFF_SECONDS * (2 ** attempt)
#                     st.warning(f"Retrying Page {page_num} in {wait_time:.1f}s due to overload...", icon="⚠️")
#                     time.sleep(wait_time)
#                 else:
#                     return {"summary": f"Page {page_num} failed after retries.", "key_points": []}
#             else:
#                 return {"summary": f"Unexpected error: {e}", "key_points": []}
#     return {"summary": "Failed to analyze this page.", "key_points": []}
# 
# def summarize_document(text: str) -> str:
#     prompt = (
#         "Provide a simplified overall summary of this legal document. "
#         "Explain its purpose, key obligations, and potential risks in plain English.\n\n"
#         f"Document Text:\n{text}"
#     )
#     for attempt in range(MAX_RETRIES):
#         try:
#             response = client.models.generate_content(
#                 model=MODEL_NAME,
#                 contents=[{"text": prompt}],
#                 config={"temperature": 0.2}
#             )
#             return response.text.strip()
#         except Exception as e:
#             if "503" in str(e) or "rate limit" in str(e).lower():
#                 if attempt < MAX_RETRIES - 1:
#                     wait_time = INITIAL_BACKOFF_SECONDS * (2 ** attempt)
#                     st.warning(f"Retrying summary in {wait_time:.1f}s...", icon="⚠️")
#                     time.sleep(wait_time)
#                 else:
#                     return "Failed to generate summary after multiple retries."
#             else:
#                 return f"Error generating summary: {e}"
#     return "Could not generate summary."
# 
# def answer_question(document_text: str, question: str, is_document_present: bool) -> str:
#     base_prompt = "You are LawMate, an expert legal AI. Answer the following question in a clear, concise, and non-legalistic way. "
#     question_lower = question.lower()
# 
#     general_law_keywords = ["ipc", "crpc", "section", "act", "law", "statute", "constitution", "code"]
#     is_general_law_query = any(k in question_lower for k in general_law_keywords)
# 
#     if re.search(r'\b(ipc|crpc|section|sec\.|art\.|article)\s*\d+', question_lower):
#         is_general_law_query = True
# 
#     doc_specific_keywords = ["this document", "this agreement", "this contract", "as per the document", "in the file"]
#     is_doc_specific_phrase = any(k in question_lower for k in doc_specific_keywords)
# 
#     if is_document_present and is_doc_specific_phrase:
#         prompt = (
#             base_prompt +
#             f"Base your answer strictly on the document text provided below. If the question cannot be answered by the document, clearly state that the information is not in the document.\n\n"
#             f"Question: {question}\n\n"
#             f"Document Text:\n{document_text}"
#         )
#     elif is_general_law_query and not is_doc_specific_phrase:
#         prompt = (
#             base_prompt +
#             f"Use your vast knowledge base of laws and legal concepts to answer. Explain the law or section in simple, non-technical terms. Do not mention any uploaded document.\n\n"
#             f"Question: {question}"
#         )
#     elif is_document_present:
#         prompt = (
#             base_prompt +
#             f"Base your answer on the document text provided below, but if the question is clearly about a general law (like an IPC section), use your general knowledge instead. Do not mix information. If the answer is not in the document, state it.\n\n"
#             f"Question: {question}\n\n"
#             f"Document Text:\n{document_text}"
#         )
#     else:
#         prompt = (
#             base_prompt +
#             f"Use your vast knowledge base of laws and legal concepts to answer. Explain the law or section in simple, non-technical terms.\n\n"
#             f"Question: {question}"
#         )
# 
#     try:
#         response = client.models.generate_content(
#             model=MODEL_NAME,
#             contents=[{"text": prompt}],
#             config={"temperature": 0.1}
#         )
#         return response.text.strip()
#     except Exception as e:
#         return f"An error occurred while trying to answer: {e}"
# 
# def extract_text_from_pdf(file_bytes: bytes):
#     pages_with_text = []
#     try:
#         reader = PdfReader(io.BytesIO(file_bytes))
#         total_pages = len(reader.pages)
#         st.info(f"📚 Found {total_pages} pages in the PDF. Extracting text...", icon="🔍")
#         progress = st.progress(0)
#         for i, page in enumerate(reader.pages, start=1):
#             text = page.extract_text() or ""
#             pages_with_text.append((i, text.strip()))
#             progress.progress(i / total_pages)
#         progress.empty()
#         return pages_with_text
#     except Exception as e:
#         st.error(f"Failed to extract text: {e}", icon="🚫")
#         return []
# 
# if 'analysis_done' not in st.session_state:
#     st.session_state['analysis_done'] = False
# if 'full_document_text' not in st.session_state:
#     st.session_state['full_document_text'] = ""
# if 'page_summaries' not in st.session_state:
#     st.session_state['page_summaries'] = []
# if 'overall_summary' not in st.session_state:
#     st.session_state['overall_summary'] = ""
# if 'is_document_uploaded' not in st.session_state:
#     st.session_state['is_document_uploaded'] = False
# 
# uploaded_file = st.file_uploader("Upload a legal document (PDF or TXT)", type=["pdf", "txt"])
# st.session_state['is_document_uploaded'] = (uploaded_file is not None)
# 
# if not uploaded_file:
#     st.markdown('<div class="info-box">Upload a PDF or TXT to analyze a document, or use the chat box below to ask general law questions (e.g., "What is IPC 420?").</div>', unsafe_allow_html=True)
# 
#     st.session_state['analysis_done'] = False
#     st.session_state['full_document_text'] = ""
#     st.session_state['page_summaries'] = []
#     st.session_state['overall_summary'] = ""
# 
# if uploaded_file:
#     if 'last_uploaded_file_name' not in st.session_state or st.session_state['last_uploaded_file_name'] != uploaded_file.name:
#         st.session_state['analysis_done'] = False
#         st.session_state['last_uploaded_file_name'] = uploaded_file.name
# 
#     file_bytes = uploaded_file.read()
#     if uploaded_file.type == "application/pdf":
#         pages = extract_text_from_pdf(file_bytes)
#     else:
#         pages = [(1, file_bytes.decode("utf-8"))]
# 
#     processable_pages = [(p, t) for p, t in pages if t.strip()]
# 
#     if st.button("🔍 Analyze Document", use_container_width=True) or (uploaded_file and not st.session_state['analysis_done']):
#         if not processable_pages:
#             st.warning("This document appears empty or unprocessable.", icon="⚠️")
#             st.session_state['analysis_done'] = True
#         else:
#             total_pages = len(processable_pages)
#             st.info(f"Analyzing {total_pages} page(s)... please wait ⏳", icon="➡️")
#             progress_bar = st.progress(0)
#             status_text = st.empty()
#             page_summaries_temp = []
# 
#             if total_pages <= 15:
#                 st.session_state['full_document_text'] = " ".join([text for _, text in processable_pages])
#                 for i, (page_num, text) in enumerate(processable_pages):
#                     progress_bar.progress((i + 1) / total_pages)
#                     status_text.text(f"Summarizing Page {page_num} of {total_pages}...")
#                     result = analyze_page(text, page_num)
#                     # Ensure key_points exists and is a list
#                     if not isinstance(result.get("key_points"), list):
#                         result["key_points"] = []
#                     page_summaries_temp.append((page_num, result))
# 
#                 overall = summarize_document(st.session_state['full_document_text'])
#             else:
#                 st.warning("Large document detected (>15 pages). Splitting for efficient processing.", icon="⚙️")
#                 section_size = 10
#                 total_sections = (total_pages + section_size - 1) // section_size
#                 section_summaries = []
# 
#                 for section_idx in range(total_sections):
#                     start_idx = section_idx * section_size
#                     end_idx = min((section_idx + 1) * section_size, total_pages)
#                     section_pages = processable_pages[start_idx:end_idx]
#                     section_text = " ".join([t for _, t in section_pages])
#                     status_text.text(f"Summarizing Section {section_idx + 1} ({start_idx + 1}–{end_idx})...")
#                     section_summary = summarize_document(section_text)
#                     section_summaries.append(f"Section {section_idx + 1}: {section_summary}")
#                     page_summaries_temp.append((section_idx + 1, {"summary": section_summary, "key_points": []}))
#                     progress_bar.progress(end_idx / total_pages)
# 
#                 st.session_state['full_document_text'] = " ".join(section_summaries)
#                 status_text.text("Generating overall simplified summary from sections...")
#                 overall = summarize_document(st.session_state['full_document_text'])
# 
#             status_text.success("Analysis complete!", icon="✅")
#             progress_bar.empty()
# 
#             st.session_state['analysis_done'] = True
#             st.session_state['page_summaries'] = page_summaries_temp
#             st.session_state['overall_summary'] = overall
# 
#     if st.session_state['analysis_done'] and st.session_state['is_document_uploaded']:
#         st.markdown("### Detailed Section/Page Summaries")
#         for page_num, res in st.session_state['page_summaries']:
#             title_prefix = "Page" if res.get("key_points") else "Section"
#             with st.expander(f" {title_prefix} {page_num} Summary", expanded=False):
#                 st.markdown(f"<p>{res.get('summary', 'No summary available.')}</p>", unsafe_allow_html=True)
#                 if res.get("key_points"):
#                     st.markdown("<strong>Key Points:</strong>", unsafe_allow_html=True)
#                     st.markdown("<ul>", unsafe_allow_html=True)
#                     for point in res["key_points"]:
#                         st.markdown(f"<li>{point}</li>", unsafe_allow_html=True)
#                     st.markdown("</ul>", unsafe_allow_html=True)
# 
#         st.markdown("---")
#         st.markdown(f"<div class='card'><div class='section-title'>📘 Overall Simplified Summary</div><p>{st.session_state['overall_summary']}</p></div>", unsafe_allow_html=True)
#         st.markdown("---")
# 
# 
#         try:
# 
#             sns.set_style("darkgrid")
#             plt.rcParams["figure.facecolor"] = "#0d1117"
#             plt.rcParams["axes.facecolor"] = "#161b22"
#             plt.rcParams["savefig.facecolor"] = "#0d1117"
#             plt.rcParams["text.color"] = "#c9d1d9"
#             plt.rcParams["axes.labelcolor"] = "#c9d1d9"
#             plt.rcParams["xtick.color"] = "#c9d1d9"
#             plt.rcParams["ytick.color"] = "#c9d1d9"
#             plt.rcParams["axes.edgecolor"] = "#30363d"
# 
# 
#             data = []
#             for page_num, summary in st.session_state['page_summaries']:
#                 summary_text = summary.get("summary", "") or ""
#                 key_points = summary.get("key_points", []) or []
#                 # In case key_points is not a list (defensive)
#                 if not isinstance(key_points, list):
#                     try:
#                         key_points = list(key_points)
#                     except Exception:
#                         key_points = []
#                 data.append({
#                     "Page": int(page_num),
#                     "SummaryLength": len(summary_text),
#                     "KeyPoints": len(key_points),
#                     "SummaryText": summary_text
#                 })
# 
#             if data:
#                 df = pd.DataFrame(data).sort_values("Page")
# 
#                 st.markdown("## 📊 Visual Insights from Document")
# 
# 
#                 st.markdown("### 📝 Summary Length per Page")
#                 fig1, ax1 = plt.subplots(figsize=(10, 4))
#                 sns.barplot(x="Page", y="SummaryLength", data=df, ax=ax1)
#                 ax1.set_xlabel("Page Number")
#                 ax1.set_ylabel("Summary Length (characters)")
#                 ax1.set_title("Summary Length Across Pages")
#                 ax1.grid(True, alpha=0.25)
#                 st.pyplot(fig1)
#                 plt.close(fig1)
# 
#                 st.markdown("### 🔑 Number of Key Points per Page")
#                 fig2, ax2 = plt.subplots(figsize=(10, 4))
#                 sns.barplot(x="Page", y="KeyPoints", data=df, ax=ax2)
#                 ax2.set_xlabel("Page Number")
#                 ax2.set_ylabel("Key Points Count")
#                 ax2.set_title("Key Points Distribution")
#                 ax2.grid(True, alpha=0.25)
#                 st.pyplot(fig2)
#                 plt.close(fig2)
# 
# 
#                 st.markdown("### 📘 Content Density (Summary Length ÷ (Key Points + 1))")
#                 df["Density"] = df["SummaryLength"] / (df["KeyPoints"] + 1)
#                 fig3, ax3 = plt.subplots(figsize=(10, 4))
#                 sns.lineplot(x="Page", y="Density", data=df, marker="o", ax=ax3)
#                 ax3.set_xlabel("Page Number")
#                 ax3.set_ylabel("Content Density Score")
#                 ax3.set_title("Content Density Per Page")
#                 ax3.grid(True, alpha=0.25)
#                 st.pyplot(fig3)
#                 plt.close(fig3)
# 
# 
#                 with st.expander("Show raw page metrics table", expanded=False):
#                     st.dataframe(df[["Page", "SummaryLength", "KeyPoints", "Density"]].reset_index(drop=True))
# 
#         except Exception as e:
#             st.error(f"Could not render visualizations: {e}", icon="🚫")
# 
# st.markdown('<div class="section-title">💬 Ask LawMate a Question (Document or General Law)</div>', unsafe_allow_html=True)
# 
# if st.session_state['is_document_uploaded']:
#     st.markdown("Ask about the **uploaded document** (e.g., 'What are the termination rights?') or a **general law** (e.g., 'What is IPC 302?').")
# else:
#     st.markdown("Ask about any **general law** or legal concept (e.g., 'What is IPC 420?' or 'Explain civil law vs. criminal law').")
# 
# question = st.text_input(
#     "Your Legal Question:",
#     placeholder="e.g., What is IPC Section 420?",
#     key="user_question"
# )
# 
# if st.button("⚖️ Get AI Answer", key="get_answer_btn", use_container_width=True):
#     if question.strip():
#         with st.spinner("LawMate is retrieving the legal information..."):
#             doc_context = st.session_state['full_document_text'] if st.session_state['is_document_uploaded'] else ""
#             answer = answer_question(
#                 document_text=doc_context,
#                 question=question,
#                 is_document_present=st.session_state['is_document_uploaded']
#             )
#         st.markdown("#### LawMate's Answer:")
#         st.info(answer, icon="💡")
#     else:
#         st.warning("Please enter a question to get an answer.", icon="❓")
# 
# st.markdown("""
#     <div class="footer">
#         ⚠️ <strong>Disclaimer:</strong> AI summaries and answers are for informational purposes only. Always consult a lawyer for real legal advice.<br>
#         Built with ❤️ and Streamlit.
#     </div>
# """, unsafe_allow_html=True)
#